Human.create(name: 'Human')
Novice.create(name: 'Novice computer')
Standard.create(name: 'Standard computer')
Intermediate.create(name: 'Intermediate computer')
Advanced.create(name: 'Advanced computer')
