Human.create(name: 'Human')
Dumb.create(name: 'Dumb computer')
Standard.create(name: 'Standard computer')
Intermediate.create(name: 'Intermediate computer')
Advanced.create(name: 'Advanced computer')
